name: getx_translator
description: For generating language strings file for Flutter. Easy translation with google sheet.
version: 1.0.3
homepage: https://github.com/bikram0000/getx_translator
repository: https://github.com/bikram0000/getx_translator

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  http: ^1.3.0
  yaml: ^3.1.3
  args: ^2.6.0
  logger: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
